# 
# Do not Edit! Generated by:
# spectacle version 0.13
# 
# >> macros
# << macros

Name:       chrpath
Summary:    Modify rpath of compiled programs
Version:    0.13
Release:    3
Group:      Development/Tools
License:    GPL+
URL:        http://www.tux.org/pub/X-Windows/ftp.hungry.com/chrpath/
Source0:    http://www.tux.org/pub/X-Windows/ftp.hungry.com/chrpath/%{name}-%{version}.tar.gz
Source100:  chrpath.yaml

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
chrpath allows you to modify the dynamic library load path (rpath) of
compiled programs.  Currently, only removing and modifying the rpath
is supported.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -fr %{buildroot}/usr/doc


# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING README 
%{_bindir}/chrpath
%doc %{_mandir}/man1/chrpath.1*
# << files


